// Code generated by MockGen. DO NOT EDIT.
// Source: ./handler.go

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	model "github.com/dev-pt-bai/cataloging/internal/model"
	errors "github.com/dev-pt-bai/cataloging/internal/pkg/errors"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssignUserRole mocks base method.
func (m *MockService) AssignUserRole(ctx context.Context, role model.Role, ID string) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserRole", ctx, role, ID)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// AssignUserRole indicates an expected call of AssignUserRole.
func (mr *MockServiceMockRecorder) AssignUserRole(ctx, role, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserRole", reflect.TypeOf((*MockService)(nil).AssignUserRole), ctx, role, ID)
}

// CreateUser mocks base method.
func (m *MockService) CreateUser(ctx context.Context, user model.User) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockServiceMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockService)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockService) DeleteUser(ctx context.Context, ID string) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, ID)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockServiceMockRecorder) DeleteUser(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockService)(nil).DeleteUser), ctx, ID)
}

// GetUser mocks base method.
func (m *MockService) GetUser(ctx context.Context, ID string) (*model.User, *errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, ID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(*errors.Error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockServiceMockRecorder) GetUser(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockService)(nil).GetUser), ctx, ID)
}

// ListUsers mocks base method.
func (m *MockService) ListUsers(ctx context.Context, criteria model.ListUsersCriteria) (*model.Users, *errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, criteria)
	ret0, _ := ret[0].(*model.Users)
	ret1, _ := ret[1].(*errors.Error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockServiceMockRecorder) ListUsers(ctx, criteria interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockService)(nil).ListUsers), ctx, criteria)
}

// SendVerificationEmail mocks base method.
func (m *MockService) SendVerificationEmail(ctx context.Context, userID string) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, userID)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockServiceMockRecorder) SendVerificationEmail(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockService)(nil).SendVerificationEmail), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockService) UpdateUser(ctx context.Context, user model.User) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockServiceMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockService)(nil).UpdateUser), ctx, user)
}

// VerifyUser mocks base method.
func (m *MockService) VerifyUser(ctx context.Context, userID, code string) (*model.Auth, *errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUser", ctx, userID, code)
	ret0, _ := ret[0].(*model.Auth)
	ret1, _ := ret[1].(*errors.Error)
	return ret0, ret1
}

// VerifyUser indicates an expected call of VerifyUser.
func (mr *MockServiceMockRecorder) VerifyUser(ctx, userID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUser", reflect.TypeOf((*MockService)(nil).VerifyUser), ctx, userID, code)
}
